"use strict";
// 多长时间可以产生一个区块
const BLOCK_GENERATION_INTERVAL = 10;
// 难度调整的间隔
const DIFFICULTY_ADJUSTMENT_INTERVAL = 10;
module.exports = {
    BLOCK_GENERATION_INTERVAL,
    DIFFICULTY_ADJUSTMENT_INTERVAL
};
