"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DIFFICULTY_ADJUSTMENT_INTERVAL = exports.BLOCK_GENERATION_INTERVAL = void 0;
// 多长时间可以产生一个区块
const BLOCK_GENERATION_INTERVAL = 100;
exports.BLOCK_GENERATION_INTERVAL = BLOCK_GENERATION_INTERVAL;
// 难度调整的间隔
const DIFFICULTY_ADJUSTMENT_INTERVAL = 10;
exports.DIFFICULTY_ADJUSTMENT_INTERVAL = DIFFICULTY_ADJUSTMENT_INTERVAL;
